#!/bin/sh

SUBMISSIONS_DIR="/tmp/bismark-passive/updates"
STAGING_DIR="/tmp/bismark-passive/stage"

if [ -d "$SUBMISSIONS_DIR" ]; then
  mkdir -p $STAGING_DIR
  mv $SUBMISSIONS_DIR/* $STAGING_DIR
  scp -S "/tmp/bismark/ssh" -i $SSH_KEY $STAGING_DIR/* $USER@$SERVER:var/data/passive && rm $STAGING_DIR/*
fi
