#!/bin/sh

EXE=/tmp/usr/bin/bismark-passive.bin
IFACE=br-lan
DELAY=3
UPDATES_DIR=/tmp/bismark-passive/updates

if ! mkdir -p $UPDATES_DIR; then
    echo "Unable to create $UPDATES_DIR"
    exit 1
fi

while [ 1 ]; do
  echo "Starting Bismark Passive"
  $EXE $IFACE

  echo "Bismark-passive has exited."
  echo "Sleeping ${DELAY} seconds before restarting..."
  sleep $DELAY
done
