#!/bin/sh

EXE=/tmp/usr/bin/bismark-passive.bin
IFACE=br-lan
DELAY=10
UPDATES_DIR=/tmp/bismark-passive/updates

if ! mkdir -p $UPDATES_DIR; then
    echo "Unable to create $UPDATES_DIR"
    exit 1
fi

while [ 1 ]; do
  if ! pgrep -x $EXE; then
    echo "Starting Bismark Passive"
    $EXE $IFACE
  fi
  sleep $DELAY
done
