#!/bin/sh

. /etc/bismark/bismark.conf

SUBMISSIONS_DIR="/tmp/bismark-passive/updates"
STAGING_DIR="/tmp/bismark-passive/stage"

if [ -d "$SUBMISSIONS_DIR" ]; then
  mkdir -p $STAGING_DIR
  mv $SUBMISSIONS_DIR/* $STAGING_DIR
  sleep 1

  MANIFEST_FILE=$STAGING_DIR/`cat /etc/bismark/ID`_`date +%F_%H-%M-%S`.tar
  (cd $STAGING_DIR && tar cvf $MANIFEST_FILE *.gz)
  scp -S "/tmp/bismark/ssh" -i $SSH_KEY $MANIFEST_FILE $USER@$SERVER:var/data/passive && (rm $MANIFEST_FILE; rm $STAGING_DIR/*)
fi
